name: CI Test & Report to Jira

on:
  push:
    branches: [ main, dev-hoang ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven tests
        run: mvn -B clean test

      - name: Upload JUnit results to Xray (Jira)
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
        run: |
          TOKEN=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
            -H "Content-Type: application/json" \
            -d "{\"client_id\":\"$XRAY_CLIENT_ID\",\"client_secret\":\"$XRAY_CLIENT_SECRET\"}" | tr -d '"')

          for file in target/surefire-reports/TEST-*.xml; do
            curl -v -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=STN1" \
              -H "Authorization: Bearer $TOKEN" \
              -H "Content-Type: text/xml" \
              --data @"$file"
          done
